[credentials.usernames.ilioumbas] # Κάθε χρήστης ως ξεχωριστό "table"
email = "ilioumbas@eyath.gr"
name = "Ilias Lioumbas"
password = "$2b$12$GqL25.0tqP45CV4qgUFoU.l4Jj5vYF7n5zT9Y8h0H1L4.p1y.z8eS" # Το hash του '123'

# Για να προσθέσετε άλλον χρήστη, απλώς προσθέστε ένα νέο μπλοκ:
# [credentials.usernames.άλλο_username]
# email = "email@example.com"
# name = "Όνομα Άλλου Χρήστη"
# password = "$2b$12$xxxxxxxxxxxxxxxxxxxxxx" # Το hash του δικού του κωδικού

[cookie]
name = "eyath_wq_app_cookie_v1" # Μπορείτε να το αλλάξετε
key = "YOUR_STRONG_RANDOM_COOKIE_SIGNATURE_KEY" # <--- ΑΛΛΑΞΤΕ ΤΟ ΟΠΩΣΔΗΠΟΤΕ ΜΕ ΕΝΑ ΙΣΧΥΡΟ ΚΑΙ ΜΟΝΑΔΙΚΟ ΚΛΕΙΔΙ!
expiry_days = 30

# Προαιρετικό: Αν θέλετε να ενεργοποιήσετε τη δυνατότητα εγγραφής νέων χρηστών
# και να την περιορίσετε μόνο σε συγκεκριμένα emails:
# [preauthorized]
# emails = ["email1@example.com", "email2@example.com"]